apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  schedule:
    - cron: 41 * * * *
    - cron: 42 * * * *
    - cron: 43 * * * *
    - cron: 44 * * * *
    - cron: 45 * * * *
    - cron: 46 * * * *
    - cron: 47 * * * *
    - cron: 48 * * * *
    - cron: 49 * * * *
    - cron: 50 * * * *
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
