apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow commit to force schedule to work
on:
  schedule:
    - cron: 57 * 1 1 *
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
