apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  test-rspec:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Run test pipeline
        uses: docker://cloudbees/basic-platform:latest
        run: |-
          . /etc/codeship.sh
