apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      Name:
        type: string
        required: true
        description: Release name
      Version:
        type: number
        required: true
        description: Release version number
      Smart_deploy:
        type: boolean
        default: true
        required: true
        description: Option to do smart deploy
      Release_type:
        type: choice
        options:
          - Standard
          - Hotfix
        default: Standard
        required: true
        description: Type of release
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world ${{ inputs.Name }} ${{ inputs.Version}} ..."
